local fairmod_props = {
	{
		file = "mods/noita.fairmod/files/content/backrooms/entities/radio.xml",
		image = "mods/noita.fairmod/files/content/backrooms/entities/radio.png",
		material = "steel",
		name = "radio",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/backrooms/props/ceiling_light.xml",
		image = "mods/noita.fairmod/files/content/backrooms/props/ceiling_light.png",
		material = "ceiling_light_backrooms",
		name = "ceiling_light",
		tags = "mortal,hittable,teleportable_NOT,prop,prop_physics",
	},
	{
		file = "mods/noita.fairmod/files/content/backrooms/props/ceiling_light_broken.xml",
		image = "mods/noita.fairmod/files/content/backrooms/props/ceiling_light.png",
		material = "ceiling_light_backrooms",
		name = "ceiling_light_broken",
		tags = "mortal,hittable,teleportable_NOT,prop,prop_physics",
	},
	{
		file = "mods/noita.fairmod/files/content/backrooms/props/ceiling_light_off.xml",
		image = "mods/noita.fairmod/files/content/backrooms/props/ceiling_light_off.png",
		material = "ceiling_light_backrooms",
		name = "ceiling_light_off",
		tags = "mortal,hittable,teleportable_NOT,prop,prop_physics",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/base_cactus.xml",
		image = "data/vegetation/cactus_02.png",
		material = "cactus",
		name = "base_cactus",
		tags = "pixelsprite",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/cactus_2.xml",
		image = "data/vegetation/cactus_02.png",
		material = "cactus",
		name = "cactus_2",
		tags = "pixelsprite,cactus",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/cactus_3.xml",
		image = "data/vegetation/cactus_03.png",
		material = "cactus",
		name = "cactus_3",
		tags = "pixelsprite,cactus",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/cactus_4.xml",
		image = "data/vegetation/cactus_04.png",
		material = "cactus",
		name = "cactus_4",
		tags = "pixelsprite,cactus",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/cactus_5.xml",
		image = "data/vegetation/cactus_05.png",
		material = "cactus",
		name = "cactus_5",
		tags = "pixelsprite,cactus",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/cactus_6.xml",
		image = "data/vegetation/cactus_06.png",
		material = "cactus",
		name = "cactus_6",
		tags = "pixelsprite,cactus",
	},
	{
		file = "mods/noita.fairmod/files/content/cactus/cactus_7.xml",
		image = "data/vegetation/cactus_07.png",
		material = "cactus",
		name = "cactus_7",
		tags = "pixelsprite,cactus",
	},
	{
		file = "mods/noita.fairmod/files/content/chemical_horror/methane/physics_methane_tank.xml",
		image = "mods/noita.fairmod/files/content/chemical_horror/methane_tank.png",
		material = "steel",
		name = "physics_methane_tank",
		tags = "mortal,hittable,teleportable_NOT,prop,prop_physics",
	},
	{
		file = "mods/noita.fairmod/files/content/instruction_booklet/booklet_entity/booklet.xml",
		image = "mods/noita.fairmod/files/content/instruction_booklet/booklet_entity/booklet_in_world.png",
		material = "item_box2d_meat",
		name = "booklet",
		tags = "item_physics,item_pickup",
	},
	{
		file = "mods/noita.fairmod/files/content/snowman/snowball_item.xml",
		image = "mods/noita.fairmod/files/content/snowman/snowball_med.png",
		material = "snow_b2",
		name = "Snowball",
		tags = "hittable,teleportable_NOT,item_physics,item_pickup",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/guts/guts1.xml",
		image = "data/particles/guts_01.png",
		material = "meat",
		name = "guts1",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/guts/guts2.xml",
		image = "data/particles/guts_02.png",
		material = "meat",
		name = "guts2",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/guts/guts3.xml",
		image = "data/particles/guts_03.png",
		material = "meat",
		name = "guts3",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/guts/guts4.xml",
		image = "data/particles/guts_04.png",
		material = "meat",
		name = "guts4",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/guts/guts5.xml",
		image = "data/particles/guts_05.png",
		material = "meat",
		name = "guts5",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/base_stalactite_projectile.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_1.png",
		material = "rock_box2d",
		name = "base_stalactite_projectile",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/generic/projectile_generic_1.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/generic/stalactite_generic_1.png",
		material = "rock_box2d",
		name = "projectile_generic_1",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/generic/projectile_generic_2.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/generic/stalactite_generic_2.png",
		material = "rock_box2d",
		name = "projectile_generic_2",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/generic/projectile_generic_3.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/generic/stalactite_generic_3.png",
		material = "rock_box2d",
		name = "projectile_generic_3",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/ice/projectile_ice_1.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/ice/stalactite_ice_1.png",
		material = "ice_b2",
		name = "projectile_ice_1",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/ice/projectile_ice_2.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/ice/stalactite_ice_2.png",
		material = "ice_b2",
		name = "projectile_ice_2",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/ice/projectile_ice_3.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/ice/stalactite_ice_3.png",
		material = "ice_b2",
		name = "projectile_ice_3",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_1.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_1.png",
		material = "rock_box2d",
		name = "projectile_entrance_1",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_10.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_10.png",
		material = "rock_box2d",
		name = "projectile_entrance_10",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_11.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_11.png",
		material = "rock_box2d",
		name = "projectile_entrance_11",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_12.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_12.png",
		material = "rock_box2d",
		name = "projectile_entrance_12",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_13.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_13.png",
		material = "rock_box2d",
		name = "projectile_entrance_13",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_2.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_2.png",
		material = "rock_box2d",
		name = "projectile_entrance_2",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_3.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_3.png",
		material = "rock_box2d",
		name = "projectile_entrance_3",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_4.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_4.png",
		material = "rock_box2d",
		name = "projectile_entrance_4",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_5.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_5.png",
		material = "rock_box2d",
		name = "projectile_entrance_5",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_6.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_6.png",
		material = "rock_box2d",
		name = "projectile_entrance_6",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_7.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_7.png",
		material = "rock_box2d",
		name = "projectile_entrance_7",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_8.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_8.png",
		material = "rock_box2d",
		name = "projectile_entrance_8",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/stalactite/entities/projectiles/projectile_entrance_9.xml",
		image = "mods/noita.fairmod/files/content/stalactite/sprites/stalactite_entrance_9.png",
		material = "rock_box2d",
		name = "projectile_entrance_9",
		tags = "",
	},
	{
		file = "mods/noita.fairmod/files/content/surface_bad/propane_mine_field/propane_mine.xml",
		image = "data/props_gfx/propane_tank.png",
		material = "steel",
		name = "propane_mine",
		tags = "mortal,hittable,teleportable_NOT,prop,prop_physics",
	},
}

local props = dofile_once("mods/component-explorer/spawn_data/props.lua")

for _, fp in ipairs(fairmod_props) do
	fp.origin = "noita.fairmod"
	props[#props + 1] = fp
end
