local projPool = {}
local spritePool = {}

local projPoolVanilla = {
    --"acidburst", --boring
    --"acidshot", --zzzzz
    --"acidshot_slow", --cringe
    "arrow",
    "bat",
    --"bloomshot", --lame
    "bomb",
    "bomb_cart",
    "bomb_holy",
    "cocktail",
    "bomb_holy_giga", -- pepeLaugh
    "bomb_small",
    "bossdragon",
    "bossdragon_ray",
    "buckshot",
    "bullet_poison",
    --"chaos_polymorph", --800 gorillion years later the circle might disappear and let you pass
    "chunk_of_soil",
    --"circle_acid_small", too laggy
    --"circle_blood_small",
    --"circle_lava_small",
    --"circle_water",
    "clusterbomb",
    "cocktail",
    "coward_bullet",
    "darkflame",
    "darkflame_stationary", --This is bad but so comedically bad it's funny lmao
    "dotshot",
    "dotshot_strong",
    "egg_fire",
    "egg_monster",
    "egg_purple",
    "egg_red",
    "egg_slime",
    "egg_worm",
    "enlightened_laser_dark_wand",
    "enlightened_laser_elec_wand",
    "enlightened_laser_fire_wand",
    "enlightened_laser_light_wand",
    "explosion",
    "fire_trap",
    "fireball",
    "fireball_bigfirebug",
    "fireball_firebug", 
    "fireball_ghostly",
    "flamethrower",
    "freeze_circle",
    "fungus",
    "fungus_big_explosion",
    "fungus_explosion",
    "gasblob",
    "glitter_bomb",
    "glue",
    "glue_shot",
    "grenade_leader",
    "grenade_scavenger",
    "healshot",
    "healshot_safe_haven",
    "healshot_slow",
    "hiddenshot",
    "ice",
    "iceball",
    "icethrower",
    "invisshot",
    "laser_bouncy",
    "laser_lasergun",
    "laser_spear",
    "laser_turret",
    "laserbeam",
    "laserbeam_green",
    "lavashot",
    "lightning",
    "lurkershot",
    "meteor_green",
    "machinegun_bullet_roboguard_big",
    "machinegun_bullet_slow",
    "machinegun_bullet_slower",
    "machinegun_bullet_tank",
    "machinegun_bullet_tank_super",
    "megalaser_blue",
    "megalaser_blue_beam",
    "mine",
    "mine_scavenger",
    "neutralizershot",
    "orb",
    "orb_blue",
    "orb_cursed",
    "orb_dark",
    "orb_expanding",
    "orb_green",
    "orb_green_accelerating",
    "orb_green_boss_dragon",
    "orb_green_spin",
    "orb_hearty",
    "orb_homing",
    "orb_neutral",
    "orb_pink",
    "orb_pink_big",
    "orb_pink_big_slow",
    "orb_pink_big_super",
    "orb_pink_big_super_shrapnel",
    "orb_pink_fast",
    "orb_pink_super",
    --"orb_poly",
    "orb_purple",
    "orb_swapper",
    "orb_tele",
    "orb_tiny",
    "orb_twitchy",
    "orb_weaken",
    "orb_wither",
    "orb_weaken",
    "orb_wither",
    "orbspawner",
    "orbspawner_blue",
    "orbspawner_green",
    "pebble",
    "pollen",
    "pollen_ball",
    --"polyorb",
    "present",
    "propane_tank",
    "radioactive_blob",
    "radioactive_blob_trail",
    "radioactive_liquid",
    "rain_gold",
    "remove_ground",
    "rocket_tank",
    "rocket_tiny",
    "rocket_tiny_roll",
    "sentryshot",
    "shieldshot",
    "shieldshot_small",
    "slimeblob",
    "slimetrail",
    "smalltentacle",
    "smalltentacle_melee",
    "sniperbullet",
    "soldiershot",
    "spit_trap",
    "summonshine",
    "tentacle",
    "thunder_trap",
    "thunderball",
    "thunderball_line",
    "thunderball_slow",
    "tnt",
    "wraith_glowing_laser",
    "deck/all_blackholes",
    "deck/all_deathcrosses",
    "deck/all_discs",
    --"deck/all_nukes",
    "deck/all_rockets",
    "deck/berserk_field",
    "deck/big_magic_shield_start",
    "deck/black_hole",
    "deck/black_hole_big",
    --"deck/black_hole_giga", Funny to see omega blackhole, but ultimately a bit too unfair, even for this mod
    "deck/bloodtentacle",
    "deck/bomb_detonator",
    "deck/bouncy_orb",
    "deck/bubbleshot",
    "deck/bullet",
    "deck/bullet_heavy",
    "deck/bullet_slow",
    "deck/chain_bolt",
    "deck/chainsaw",
    "deck/chaos_polymorph_field",
    "deck/charm_field",
    "deck/cloud_acid",
    "deck/cloud_blood",
    "deck/cloud_water",
    "deck/crumbling_earth",
    "deck/disc_bullet",
    "deck/disc_bullet_big",
    "deck/disc_bullet_bigger",
    "deck/grenade",
    "deck/grenade_tier_2",
    "deck/grenade_tier_3",
    "deck/infestation",
    "deck/luminous_drill",
    "deck/regeneration_field",
    "deck/sausage",
    "deck/sea_acid",
    "deck/sea_alcohol",
    "deck/sea_water",
    "deck/sea_lava",
    "deck/sea_mimic",
    "deck/spitter",
    "deck/spitter_tier_2",
    "deck/spitter_tier_3",
    "deck/swarm_wasp",
    "deck/swarm_fly",
    "deck/swarm_firebug",
    "deck/touch_gold",
    "deck/worm_shot",
    "deck/megalaser",
    "deck/light_bullet",
    "deck/pipe_bomb",
    "deck/spiral_shot",
    "deck/spore_pod",
    "deck/water",
    "deck/xray",
    "deck/wall_horizontal",
    "deck/wall_square",
    "deck/wall_vertical",
    "deck/material_cement",
    "deck/material_blood",
    "deck/lance",
    "deck/lance_holy",
}

--Adds vanilla files to proj/sprite pool
for i,proj in ipairs(projPoolVanilla) do
    table.insert(projPool, "data/entities/projectiles/" .. proj)
end

--Functions for corruption update file to pick a random file
function pickrandomspell( seed_x, seed_y )
    SetRandomSeed(seed_x + seed_y, seed_x * seed_y)
    local projFile = projPool[Random(1,#projPool)]
    return projFile
end

function pickrandomspellalt( seed_x, seed_y )
    SetRandomSeed(seed_x * seed_y, seed_x + 7 + seed_y)
    local projFile = projPool[Random(1,#projPool)]
    return projFile
end

--[[
function pickrandomsprite( seed_x, seed_y )
    SetRandomSeed(seed_x + seed_y, seed_x * seed_y)
    local spriteFile = spritePool[Random(1,#spritePool)]
    return spriteFile
end
]]--