return {
	"Dunk is bald",
	"Also try Copi's Things!",
	"Now with 100% more snails!",
	"Made with PURE HATRED",
	"We are not responsible for any psychological damage incurred by playing this mod.",
	"Touch grass.",
	"Try talking to the snail.",
	"Help me.",
	"Wear a hard hat!",
	"Pick up the phone you fool.",
	"100% fair",
	"Black sun, Blood moon. Oceans of pain are here for yooouuuuuu!!!",
	"Copiquest!",
	"(not) sponsored by Apotheosis!",
	"Read your mails!",
	"Help, I've been locked in the basement writing splashes for two mods!!!",
	"Labor of Loathing!",
	"*Your",
	"*You're",
	"CURSE OF RA!!",
	"file was changed in the watch folder",
	"Look I implemented multi line text.\nJust for this stupid fucking splash text\nAnyway I don't actually know what to write here\n:3\nHave you eaten?\nDid you drink water?\nGet up and stretch.\n...\nAnyway goodbye.\n-eba",
	"As seen in the included information booklet!",
	"Should be played while driving!",
	"May contain death!",
	"More pixels!",
	"Absolutely full of memes.",
	"0.1% bug free!",
	"Now in 2D!",
	"Wow!",
	"Also try Apotheosis!",
	"Do not mix with Noita Arena!",
	"Freaky!",
	"hated by morbillions!",
	"Uninstalled by Dunk! That's surely a recommendation.",
	"It is awful!",
	"Find maxwell.",
	"So liminal!",
	"Try code \"gullible\" to win the game!",
	"Eba was here :3",
	"Will lower your life expectancy by 12.5 years!",
	"You will survive surely!",
	"Just one more run!",
	"This is the one I can feel it.",
	"The radio holds a key, at the right time.",
	"The only mod where you can become a shit rocket!",
}