return {
	"Dunk is bald",
	"Also try Copi's Things!",
	"Now with 100% more snails!",
	"Made with PURE HATRED",
	"We are not responsible for any psychological damage incurred by playing this mod.",
	"Touch grass.",
	"Try talking to the snail.",
	"Help me.",
	"Wear a hard hat!",
	"Pick up the phone you fool.",
	"100% fair",
	"Black sun, Blood moon. Oceans of pain are here for yooouuuuuu!!!",
	"Copiquest!",
	"(not) sponsored by Apotheosis!",
}