local markers = dofile_once("mods/noita.fairmod/files/content/better_world/map_helper.lua")
return {
	{
		id = "stage0",
		name = "Back to the beginning...",
		desc = "HEY! COULDN'T YOU HAVE JUST USED \"/SPAWN\"?!",
		x = markers.cave_entrance.x,
		y = markers.cave_entrance.y,
		pw_local = true,
	},
	{
		id = "stage1",
		name = "Past the first level!",
		desc = "Stupid fuckin' Hämis :(",
		x = markers.pits_entrance.x,
		y = markers.pits_entrance.y,
		pw_local = true,
	},
	{
		id = "stage2",
		name = "Most people don't get here legit!",
		desc = "You're presumably \"Most peopl\".",
		x = markers.snowcave_entrance.x,
		y = markers.snowcave_entrance.y,
		pw_local = true,
	},
	{
		id = "stage3",
		name = "Hiisi Takeover Reference!",
		desc = "I actually don't remember what we did to this level lmao",
		x = markers.hiisi_entrance.x,
		y = markers.hiisi_entrance.y,
		pw_local = true,
	},
	{
		id = "stage4",
		name = "The Vines!",
		desc = "the vines are awful im so sorry",
		x = markers.jungle_entrance.x,
		y = markers.jungle_entrance.y,
		pw_local = true,
	},
	{
		id = "stage5",
		name = "Warzone!",
		desc = "I upped the spawns so hard its multi-layered",
		x = markers.vault_entrance.x,
		y = markers.vault_entrance.y,
		pw_local = true,
	},
	{
		id = "stage6",
		name = "TotA",
		desc = "(stands for \"Traps overdone, thanks Avaisa.\")",
		x = markers.tota_entrance.x,
		y = markers.tota_entrance.y,
		pw_local = true,
	},
	{
		id = "kantele",
		name = "Tree Nook!",
		desc = "This is a little different from what I remember...",
		x = markers.kantele_spot.x,
		y = markers.kantele_spot.y,
	}
}